import { ITimelineTweet } from '@/types/timeline.type';
import { ITweetAuthor, ITweetInteraction } from '@/types/tweet.type';

const tweetAuthor: ITweetAuthor = {
  id: '1',
  handle: 'sam_d_coder',
  name: 'Ugonna Asemota',
  avatar:
    'https://pbs.twimg.com/profile_images/1624061840660520960/R2DzPe0c_normal.jpg',
  has_custom_timelines: false,
  url: 'https://twitter.com/sam_d_coder',
  verified: true,
};

export const timelineTweets: ITimelineTweet[] = [
  {
    id: '1',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.QUOTE_TWEET,
    is_pinned: false,
    is_quote_tweet: true,
    is_retweet: false,
    is_reply_tweet: false,
    quoted_tweet: {
      id: '2',
      content:
        'Excited to dive into some new coding challenges! 💻 #codingadventures',
      quote_count: 2,
      reply_count: 8,
      timestamp: '2021-07-21T12:00:00.000Z',
      repost_count: 10,
      favorite_count: 156,
      bookmark_count: 7,
      author: tweetAuthor,
      type: ITweetInteraction.TWEET,
      is_pinned: false,
      is_quote_tweet: false,
      is_retweet: false,
      is_reply_tweet: false,
    },
  },
  {
    id: '2',
    content:
      'Excited to dive into some new coding challenges! 💻 #codingadventures',
    quote_count: 2,
    reply_count: 8,
    timestamp: '2021-07-21T12:00:00.000Z',
    repost_count: 10,
    favorite_count: 156,
    bookmark_count: 7,
    author: tweetAuthor,
    type: ITweetInteraction.RETWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '10',
    content:
      'Just wrapped up a great week of coding. Time to relax! #weekendvibes',
    quote_count: 3,
    reply_count: 7,
    repost_count: 20,
    favorite_count: 150,
    bookmark_count: 8,
    author: tweetAuthor,
    type: ITweetInteraction.LIKE,
    timestamp: '2021-07-20T15:00:00.000Z',
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '3',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.RETWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '4',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.REPLY,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '5',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.TWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '6',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.TWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '7',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.TWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '8',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.TWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '9',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.TWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
  {
    id: '10',
    content: 'Just started a new project today! #coding #javascript',
    quote_count: 5,
    reply_count: 10,
    timestamp: '2021-07-20T15:00:00.000Z',
    repost_count: 15,
    favorite_count: 239,
    bookmark_count: 11,
    author: tweetAuthor,
    type: ITweetInteraction.TWEET,
    is_pinned: false,
    is_quote_tweet: false,
    is_retweet: false,
    is_reply_tweet: false,
  },
].map((tweet) => ({
  ...tweet,
  id: Math.floor(Math.random() * 1000).toString(),
  quote_count: Math.floor(Math.random() * 20),
  reply_count: Math.floor(Math.random() * 50),
  timestamp: new Date().toISOString(),
  repost_count: Math.floor(Math.random() * 30),
  favorite_count: Math.floor(Math.random() * 500),
  bookmark_count: Math.floor(Math.random() * 20),
}));
